### ISSUE TITLE
URLs don't respect base_path

### ISSUE THREAD

**Issue by meowcat** [datasette/datasette-write-ui#14]
Running datasette with `--setting base_url /my-instance/`, the "insert row" button doesn't work and the GET requests for JS, CSS go to

`https://my-server/-/static-plugins/datasette_write_ui/table.min.js`
instead of
`https://my-server/my-instance/-/static-plugins/datasette_write_ui/table.min.js`

**Comment by simonw** [comment]
This should be fixed now, and the fix is released in `0.0.1a8` - re-open this issue if it doesn't work for you!
